[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "22"
  CI = "false"
  NPM_FLAGS = "--legacy-peer-deps"
  GENERATE_SOURCEMAP = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
